from setuptools import setup, find_packages

setup(
      name='adtdataplane',
      version='0.1',
      description='ADT data plane python SDK',
      author='Azure Digital Twin autogenerated using autorest by Paul Hernandez',
      url='https://github.com/pauldj54/ADTDataPlane',
      packages=find_packages(exclude=['tests*'])
      )
      